version: '2'
services:
  wordpress:
    image: 665606761254.dkr.ecr.us-east-1.amazonaws.com/personal:latest
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial-personal
        awslogs-region: us-east-1
        awslogs-stream-prefix: personal
